[unstable]
build-std = ["core", "compiler_builtins"]
# Include needed functions ( memset, memcmp, memcpy ... )
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-veer.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"